# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

YELP_CONSUMER_KEY: FAWYz3fLKNkJk8y9hov-HQ
YELP_CONSUMER_SECRET: IMSJ9Gtj-N4C7LiOeOOu8i3YVnk
YELP_TOKEN: 6gU0xJzU096r-ImUQXV5694Vj7RLipDk
YELP_TOKEN_SECRET: s8SSdbNje6DN5Q4EfAtM7YgRye4
